# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import strategy_pb2 as proto_dot_strategy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/strategy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonStrategyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/engine.PythonStrategy/Execute',
                request_serializer=proto_dot_strategy__pb2.StrategyRequest.SerializeToString,
                response_deserializer=proto_dot_strategy__pb2.StrategyResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/engine.PythonStrategy/Train',
                request_serializer=proto_dot_strategy__pb2.TrainRequest.SerializeToString,
                response_deserializer=proto_dot_strategy__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/engine.PythonStrategy/GetMetadata',
                request_serializer=proto_dot_strategy__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_strategy__pb2.StrategyMetadataResponse.FromString,
                _registered_method=True)


class PythonStrategyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonStrategyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=proto_dot_strategy__pb2.StrategyRequest.FromString,
                    response_serializer=proto_dot_strategy__pb2.StrategyResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=proto_dot_strategy__pb2.TrainRequest.FromString,
                    response_serializer=proto_dot_strategy__pb2.TrainResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=proto_dot_strategy__pb2.Empty.FromString,
                    response_serializer=proto_dot_strategy__pb2.StrategyMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.PythonStrategy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.PythonStrategy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonStrategy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.PythonStrategy/Execute',
            proto_dot_strategy__pb2.StrategyRequest.SerializeToString,
            proto_dot_strategy__pb2.StrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.PythonStrategy/Train',
            proto_dot_strategy__pb2.TrainRequest.SerializeToString,
            proto_dot_strategy__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.PythonStrategy/GetMetadata',
            proto_dot_strategy__pb2.Empty.SerializeToString,
            proto_dot_strategy__pb2.StrategyMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
