from concurrent import futures
import time
import json
import logging
import grpc

from src.strategies.sentiment_mock import MockSentimentStrategy

# Generated by proto compiler
import proto.strategy_pb2 as strategy_pb2
import proto.strategy_pb2_grpc as strategy_pb2_grpc

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class PythonStrategyServicer(strategy_pb2_grpc.PythonStrategyServicer):
    
    def __init__(self):
        self.strategies = {
            "python-sentiment-mock": MockSentimentStrategy()
        }

    def Execute(self, request, context):
        strat_id = request.strategy_id
        
        if strat_id not in self.strategies:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(f"Strategy {strat_id} not found on Python engine")
            return strategy_pb2.StrategyResponse()

        strat = self.strategies[strat_id]
        
        try:
            input_data = json.loads(request.input_json)
            params = dict(request.params)
            
            start_time = time.time()
            output_dict, confidence = strat.execute(input_data, params)
            elapsed_ms = int((time.time() - start_time) * 1000)
            
            return strategy_pb2.StrategyResponse(
                output_json=json.dumps(output_dict),
                confidence=confidence,
                execution_time_ms=str(elapsed_ms)
            )
        except Exception as e:
            logger.error(f"Error executing strategy {strat_id}: {e}")
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return strategy_pb2.StrategyResponse()

    def Train(self, request, context):
        """Receives training data from the Java engine and delegates to the strategy."""
        strat_id = request.strategy_id
        
        if strat_id not in self.strategies:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(f"Strategy {strat_id} not found for training")
            return strategy_pb2.TrainResponse(status="FAILED", new_accuracy=0.0)

        strat = self.strategies[strat_id]
        
        try:
            training_data = json.loads(request.training_data_json)
            new_accuracy = strat.train(training_data)
            logger.info(f"Training completed for {strat_id}. New accuracy: {new_accuracy}")
            return strategy_pb2.TrainResponse(status="SUCCESS", new_accuracy=new_accuracy)
        except Exception as e:
            logger.error(f"Training failed for {strat_id}: {e}")
            return strategy_pb2.TrainResponse(status="FAILED", new_accuracy=0.0)

    def GetMetadata(self, request, context):
        """Returns metadata for the first available strategy (or generic if none)."""
        if self.strategies:
            first_strat = next(iter(self.strategies.values()))
            return strategy_pb2.StrategyMetadataResponse(
                version=first_strat.version,
                description=first_strat.description
            )
        return strategy_pb2.StrategyMetadataResponse(
            version="unknown",
            description="No strategies registered"
        )

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    strategy_pb2_grpc.add_PythonStrategyServicer_to_server(PythonStrategyServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    logger.info("Python gRPC Engine listening on port 50051...")
    server.wait_for_termination()

if __name__ == '__main__':
    serve()
