# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/strategy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/strategy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/strategy.proto\x12\x06\x65ngine\"\x9e\x01\n\x0fStrategyRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x12\n\ninput_json\x18\x02 \x01(\t\x12\x33\n\x06params\x18\x03 \x03(\x0b\x32#.engine.StrategyRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"V\n\x10StrategyResponse\x12\x13\n\x0boutput_json\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x19\n\x11\x65xecution_time_ms\x18\x03 \x01(\t\"?\n\x0cTrainRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x1a\n\x12training_data_json\x18\x02 \x01(\t\"5\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cnew_accuracy\x18\x02 \x01(\x01\"\x07\n\x05\x45mpty\"@\n\x18StrategyMetadataResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xc4\x01\n\x0ePythonStrategy\x12<\n\x07\x45xecute\x12\x17.engine.StrategyRequest\x1a\x18.engine.StrategyResponse\x12\x34\n\x05Train\x12\x14.engine.TrainRequest\x1a\x15.engine.TrainResponse\x12>\n\x0bGetMetadata\x12\r.engine.Empty\x1a .engine.StrategyMetadataResponseB8\n%com.custodyreport.backend.engine.grpcB\rStrategyProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.strategy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.custodyreport.backend.engine.grpcB\rStrategyProtoP\001'
  _globals['_STRATEGYREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_STRATEGYREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_STRATEGYREQUEST']._serialized_start=33
  _globals['_STRATEGYREQUEST']._serialized_end=191
  _globals['_STRATEGYREQUEST_PARAMSENTRY']._serialized_start=146
  _globals['_STRATEGYREQUEST_PARAMSENTRY']._serialized_end=191
  _globals['_STRATEGYRESPONSE']._serialized_start=193
  _globals['_STRATEGYRESPONSE']._serialized_end=279
  _globals['_TRAINREQUEST']._serialized_start=281
  _globals['_TRAINREQUEST']._serialized_end=344
  _globals['_TRAINRESPONSE']._serialized_start=346
  _globals['_TRAINRESPONSE']._serialized_end=399
  _globals['_EMPTY']._serialized_start=401
  _globals['_EMPTY']._serialized_end=408
  _globals['_STRATEGYMETADATARESPONSE']._serialized_start=410
  _globals['_STRATEGYMETADATARESPONSE']._serialized_end=474
  _globals['_PYTHONSTRATEGY']._serialized_start=477
  _globals['_PYTHONSTRATEGY']._serialized_end=673
# @@protoc_insertion_point(module_scope)
